'use strict';
const LIVE_URL='./top3-live.json';
const state={draws:[],days:14,rowLimit:50,mode:'ALL',activeDigits:new Set(),tab:'matrix',updatedAt:null,source:'встроенный архив'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const WEEK=['Вс','Пн','Вт','Ср','Чт','Пт','Сб'];
function parseDate(s){const [d,m,y]=String(s).split('.').map(Number);return new Date(Date.UTC(y<100?2000+y:y,m-1,d));}
function dateKey(d){return d.date}
function weekday(s){const dt=parseDate(s);return WEEK[dt.getUTCDay()]}
function normalizeRow(r){if(Array.isArray(r))return {id:+r[0],date:String(r[1]),time:String(r[2]),a:+r[3],b:+r[4],c:+r[5]};return {id:+r.id,date:String(r.date),time:String(r.time),a:+r.a,b:+r.b,c:+r.c}}
function valid(d){return Number.isFinite(d.id)&&/^\d{2}\.\d{2}\.\d{2}$/.test(d.date)&&/^\d{2}:\d{2}$/.test(d.time)&&[d.a,d.b,d.c].every(x=>Number.isInteger(x)&&x>=0&&x<=9)}
function unique(list){const m=new Map();for(const x of list){const d=normalizeRow(x);if(valid(d)&&!m.has(d.id))m.set(d.id,d)}return [...m.values()].sort((a,b)=>b.id-a.id)}
async function load(){const seed=Array.isArray(window.TOP3_SEED)?window.TOP3_SEED:[];let live=[];try{const r=await fetch(`${LIVE_URL}?t=${Date.now()}`,{cache:'no-store'});if(r.ok){const j=await r.json();live=j.draws||[];state.updatedAt=j.updatedAt||null;state.source=j.source||'live';}}catch(e){} state.draws=unique([...live,...seed]);$('#totalCount').textContent=state.draws.length.toLocaleString('ru-RU'); updateStatus(); renderAll();}
function updateStatus(){let txt='Обновлено: архив';if(state.updatedAt){const d=new Date(state.updatedAt);txt=`Обновлено: ${d.toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}`;}$('#updatedText').textContent=txt;}
function filteredByDays(){if(!state.draws.length)return[];const latest=parseDate(state.draws[0].date);const min=new Date(latest);min.setUTCDate(min.getUTCDate()-(state.days-1));return state.draws.filter(d=>parseDate(d.date)>=min)}
function daysGrouped(){const list=filteredByDays();const map=new Map();for(const d of list){if(!map.has(d.date))map.set(d.date,[]);map.get(d.date).push(d)}return [...map.entries()].sort((a,b)=>parseDate(b[0])-parseDate(a[0])).slice(0,state.rowLimit)}
function timeList(groups){const set=new Set();groups.forEach(([,ds])=>ds.forEach(d=>set.add(d.time)));return [...set].sort((a,b)=>a.localeCompare(b))}
function freqMap(groups,times){const f={};for(const time of times){f[time]={A:Array(10).fill(0),B:Array(10).fill(0),C:Array(10).fill(0),ALL:Array(10).fill(0)};}for(const [,ds]of groups){for(const d of ds){const vals=[d.a,d.b,d.c];['A','B','C'].forEach((p,i)=>{f[d.time][p][vals[i]]++;f[d.time].ALL[vals[i]]++;});}}return f}
function level(n,max){if(!max)return 0;const r=n/max;if(n===0)return 0;if(r<.35)return 1;if(r<.55)return 2;if(r<.75)return 3;if(r<.92)return 4;return 5}
function renderMatrix(){const groups=daysGrouped(),times=timeList(groups),freq=freqMap(groups,times);const cols=`126px repeat(${times.length},206px)`;let html=`<div class="matrix-grid" style="grid-template-columns:${cols}">`;
html+=`<div class="mcell mhead date-head date-cell"><b>Дата</b><span>день</span></div>`;for(const t of times)html+=`<div class="mcell mhead time-head"><div class="time-title">${t}</div><div class="abc-head"><span>A</span><span>B</span><span>C</span></div></div>`;
for(const [date,ds] of groups){html+=`<div class="mcell date-cell"><b>${date}</b><span>${weekday(date)}</span></div>`;const byTime=new Map(ds.map(d=>[d.time,d]));for(const t of times){const d=byTime.get(t);if(!d){html+=`<div class="mcell draw-cell"><div class="draw-id">—</div><div class="digits"><button class="matrix-digit freq-0" disabled>·</button><button class="matrix-digit freq-0" disabled>·</button><button class="matrix-digit freq-0" disabled>·</button></div></div>`;continue;} const vals=[d.a,d.b,d.c],ps=['A','B','C'];const max=Math.max(...freq[t][state.mode]);html+=`<div class="mcell draw-cell"><div class="draw-id">№${d.id}</div><div class="digits">`+vals.map((v,i)=>{const key=state.mode==='ALL'?'ALL':state.mode;const count=freq[t][key][v];const lv=level(count,max);const dim=state.mode!=='ALL'&&state.mode!==ps[i]?' dim':'';const sel=state.activeDigits.has(v)?' selected':'';return `<button class="matrix-digit freq-${lv}${dim}${sel}" data-digit="${v}" title="${ps[i]} · ${count} раз">${v}</button>`}).join('')+`</div></div>`;}}
html+='</div>';$('#matrixTable').innerHTML=html;bindDigitClicks($('#matrixTable'));renderMatrixStatus(groups,times);renderBars(filteredByDays());}
function renderMatrixStatus(groups,times){const latest=state.draws[0];$('#matrixStatus').innerHTML=`Режим: <b>${state.mode==='ALL'?'ВСЕ':state.mode}</b><br>Дней: <b>${groups.length}</b><br>Времён: <b>${times.length}</b><br>Последний: <b>${latest?`№${latest.id}`:'—'}</b><br>Источник: <b>${state.source}</b>`}
function renderBars(list){const c=Array(10).fill(0);list.forEach(d=>{c[d.a]++;c[d.b]++;c[d.c]++});const max=Math.max(...c,1);$('#frequencyBars').innerHTML=c.map((v,i)=>`<div class="bar-wrap"><span class="bar-value">${v}</span><div class="bar" style="height:${Math.max(4,v/max*120)}px"></div><span class="bar-label">${i}</span></div>`).join('')}
function renderActiveDigits(){for(const id of ['topDigitButtons','activeDigitButtons']){const el=$('#'+id);el.innerHTML=Array.from({length:10},(_,i)=>`<button class="digit-btn ${state.activeDigits.has(i)?'active':''}" data-digit="${i}">${i}</button>`).join('');bindDigitClicks(el)}$('#selectedCount').textContent=`Выбрано: ${state.activeDigits.size} / 10`}
function bindDigitClicks(root){root.querySelectorAll('[data-digit]').forEach(b=>b.onclick=()=>{const n=+b.dataset.digit;state.activeDigits.has(n)?state.activeDigits.delete(n):state.activeDigits.add(n);renderAll()})}
function renderHorizontal(){const list=filteredByDays().slice(0,state.rowLimit);$('#horizontalBody').innerHTML=list.map(d=>`<tr><td>№${d.id}</td><td>${d.date} <span class="weekday">${weekday(d.date)}</span></td><td>${d.time}</td><td><div class="combo-buttons">${[d.a,d.b,d.c].map(v=>`<button class="h-digit ${state.activeDigits.has(v)?'selected':''}" data-digit="${v}">${v}</button>`).join('')}</div></td></tr>`).join('');bindDigitClicks($('#horizontalBody'))}
function topDigitForPosition(list,pos){const c=Array(10).fill(0);list.forEach(d=>c[d[pos]]++);let best=0;for(let i=1;i<10;i++)if(c[i]>c[best])best=i;return{digit:best,count:c[best],counts:c}}
function formulaVotes(){const [d2,d1]=state.draws; if(!d1||!d2)return null;const x=[d1.a,d1.b,d1.c],y=[d2.a,d2.b,d2.c];const ops=[];const add=(name,a,b,c)=>ops.push({name,out:[a%10,b%10,c%10]});
add('перенос A2-B2-C2',y[0],y[1],y[2]);add('A1+B1 | B2 | B1',x[0]+x[1],y[1],x[1]);add('D-F-(A+B)',y[0],y[2],x[0]+x[1]);add('разности',Math.abs(x[0]-y[1]),x[2],Math.abs(x[1]-y[1]));add('суммы по зонам',x[0]+y[0],x[1]+y[1],x[2]+y[2]);add('перекрёстные суммы',x[0]+y[1],x[1]+y[2],x[2]+y[0]);
const votes=[Array(10).fill(0),Array(10).fill(0),Array(10).fill(0)];ops.forEach(o=>o.out.forEach((v,i)=>votes[i][v]++));const picks=votes.map(arr=>arr.indexOf(Math.max(...arr)));return{ops,votes,picks,combo:picks.join('')}}
function renderAI(){const list=filteredByDays();const A=topDigitForPosition(list,'a'),B=topDigitForPosition(list,'b'),C=topDigitForPosition(list,'c');const groups=daysGrouped(),times=timeList(groups),freq=freqMap(groups,times);const byTime=times.map(t=>{const all=freq[t].ALL;const d=all.indexOf(Math.max(...all));return[t,d,all[d]]});const fv=formulaVotes();let html=`<div class="ai-box"><h3>A (первая)</h3><div class="ai-big">${A.digit}</div><div>${A.count} выходов в окне</div></div><div class="ai-box"><h3>B (вторая)</h3><div class="ai-big">${B.digit}</div><div>${B.count} выходов в окне</div></div><div class="ai-box"><h3>C (третья)</h3><div class="ai-big">${C.digit}</div><div>${C.count} выходов в окне</div></div><div class="ai-box"><h3>Частотная сборка</h3><div class="ai-big">${A.digit}${B.digit}${C.digit}</div><div>не прогноз, а максимум частоты A/B/C</div></div>`;
html+=`<div class="ai-box"><h3>По времени</h3>${byTime.slice(0,12).map(x=>`<div class="ai-row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>`;
if(fv){html+=`<div class="ai-box"><h3>Формулы A1 B1 C1 → A2 B2 C2</h3>${fv.picks.map((v,i)=>`<div class="ai-row"><span>${['A3','B3','C3'][i]}</span><b>${v} · ${Math.max(...fv.votes[i])} голосов</b></div>`).join('')}</div><div class="ai-box"><h3>Сборка формул</h3><div class="ai-big">${fv.combo}</div><div>голосование ${fv.ops.length} простых формул</div></div><div class="ai-box"><h3>Важно</h3><div>Матрица показывает исторические частоты и совпадения. Результаты тиражей независимы, поэтому это аналитический сигнал, а не гарантия.</div></div>`;}$('#aiSummary').innerHTML=html}
function switchTab(tab){state.tab=tab;$$('.tab,.foot').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.view').forEach(v=>v.classList.remove('active'));$('#'+tab+'View').classList.add('active');renderAll()}
function renderAll(){renderActiveDigits();renderMatrix();renderHorizontal();renderAI()}
function bind(){$$('.tab,.foot').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('#dayButtons').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.days=+b.dataset.days;$('#dayButtons').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));renderAll()});$('#rowLimit').onchange=e=>{state.rowLimit=+e.target.value;renderAll()};$('#positionMode').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;$('#positionMode').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));renderAll()});$('#resetBtn').onclick=()=>{state.activeDigits.clear();renderAll()};$('#refreshBtn').onclick=()=>location.reload()}
window.addEventListener('load',async()=>{bind();await load();setTimeout(()=>{$('#splash').classList.add('hidden');$('#app').classList.remove('hidden')},650);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})});
