'use strict';
(function(){
const AKEY='pozitron.labMatrix.branchArchive.v2',UKEY='pozitron.labMatrix.branchUi.v1',MAX=1200;
let rows=[],cur=null,draws=[],module='branch',filter='all',collapsed=false,arrows=false,auto=true,bound=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const combo=d=>d?[+d.a,+d.b,+d.c]:[],eng=()=>window.TOP3VectorBranch;
function toast(x){if(typeof window.TOP3App?.toast==='function')window.TOP3App.toast(x);else console.log(x)}
function read(k,d){try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch(e){return d}}
function save(){localStorage.setItem(AKEY,JSON.stringify(rows.slice(0,MAX)))}
function saveUi(){localStorage.setItem(UKEY,JSON.stringify({module,filter,collapsed,arrows,auto}))}
function loadUi(){rows=Array.isArray(read(AKEY,[]))?read(AKEY,[]):[];const u=read(UKEY,{});module=['branch','steps','columns'].includes(u.module)?u.module:'branch';filter=['all','hit','part','miss','pending'].includes(u.filter)?u.filter:'all';collapsed=!!u.collapsed;arrows=!!u.arrows;auto=u.auto!==false}
function norm(r){return Array.isArray(r)?{id:+r[0],date:String(r[1]),time:String(r[2]),a:+r[3],b:+r[4],c:+r[5]}:{id:+r.id,date:String(r.date),time:String(r.time),a:+r.a,b:+r.b,c:+r.c}}
function uniq(a){const m=new Map;for(const x of a){const d=norm(x);if(Number.isFinite(d.id)&&/^\d{2}\.\d{2}\.\d{2}$/.test(d.date)&&/^\d{2}:\d{2}$/.test(d.time)&&[d.a,d.b,d.c].every(n=>Number.isInteger(n)&&n>=0&&n<=9)&&!m.has(d.id))m.set(d.id,d)}return [...m.values()].sort((a,b)=>b.id-a.id)}
async function refreshData(){let live=[];try{const r=await fetch(`./top3-live.json?t=${Date.now()}`,{cache:'no-store'});if(r.ok)live=(await r.json()).draws||[]}catch(e){console.warn('branch live',e)}draws=uniq([...live,...(Array.isArray(window.TOP3_SEED)?window.TOP3_SEED:[])]);return draws}
function analyze(){try{return eng()?.analyze(draws,{maxD:14,shifts:[-2,-1,0,1,2]})||null}catch(e){console.error(e);return null}}
function late(t){if(!t)return true;const[d,m,y]=t.date.split('.'),[h,n]=t.time.split(':');return new Date(`${2000+(+y)}-${m}-${d}T${h}:${n}:00+03:00`).getTime()<=Date.now()}
function findFact(t){return draws.find(d=>d.date===t.date&&d.time===t.time)||null}
function hitDigits(p,f){const pool=[...f],out=[];for(const n of p){const i=pool.indexOf(n);if(i>=0){out.push(n);pool.splice(i,1)}}return out}
function snap(b){return b?{D:b.D,S:b.S,label:b.label,score:+b.score||0,sourceDate:b.sourceDate,sourceTime:b.sourceTime,sourceId:b.sourceId,sourceDigits:[...(b.sourceDigits||[])],lastOverlap:+b.lastOverlap||0,streak:+b.streak||0,pairDigits:[...(b.pair?.digits||[])],pairPositions:[...(b.pair?.positions||[])]}:null}
function frozen(t){return rows.find(r=>r.targetDate===t.date&&r.targetTime===t.time)||null}
function stamp(s){const d=new Date(s);return Number.isNaN(+d)?'—':d.toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function freeze(v,manual=false,silent=false){if(!v?.active||!v?.target)return null;const old=frozen(v.target);if(old)return old;if(findFact(v.target)){if(!silent)toast('Факт уже есть — frozen не создаётся.');return null}if(late(v.target)){if(!silent)toast('Время тиража уже наступило — frozen закрыт.');return null}const r={schema:2,id:`branch-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,createdAt:new Date().toISOString(),locked:true,manual,targetDrawId:v.target.id,targetDate:v.target.date,targetTime:v.target.time,decision:v.decision,branch:snap(v.active),controlS0:snap(v.controlS0),extended:snap(v.extendedSignal),forecastDigits:v.picks.map(x=>+x.digit),latestAtFreeze:v.latest?{id:v.latest.id,date:v.latest.date,time:v.latest.time,digits:combo(v.latest)}:null,status:'pending',fact:null,matchedDigits:[],hitCount:null,sourceOverlap:null};rows=[r,...rows].slice(0,MAX);save();if(!silent)toast(`Frozen: ${r.targetTime} · ${r.forecastDigits.join(' и ')}`);return r}
function settle(show=false){let n=0;rows=rows.map(r=>{if(r.status!=='pending'||r.fact)return r;const d=draws.find(x=>x.date===r.targetDate&&x.time===r.targetTime);if(!d)return r;const fact=combo(d),matched=hitDigits(r.forecastDigits||[],fact),h=matched.length;n++;return{...r,fact,factDrawId:d.id,checkedAt:new Date().toISOString(),matchedDigits:matched,hitCount:h,sourceOverlap:eng()?.overlapArrays(r.branch?.sourceDigits||[],fact),status:h>=2?'hit':h===1?'part':'miss'}});if(n)save();if(show)toast(n?`Проверено фактов: ${n}`:'Новых фактов нет.');return n}
function digit(n,c=''){return `<span class="branch-digit ${c}">${E(n)}</span>`}
function triple(a,sel=[]){return `<div class="branch-triplet">${(a||[]).map((n,i)=>digit(n,sel.includes(i)?'selected':'')).join('')}</div>`}
function pair(a){return `<div class="branch-pair">${(a||[]).map(n=>digit(n,'forecast')).join('')}</div>`}
function sub(title,b){return `<div class="branch-subcard"><div><b>${E(title)}</b><span>${b?`${E(b.label)} · ${E(b.sourceDate)} ${E(b.sourceTime)}`:'нет сигнала'}</span></div>${b?triple(b.sourceDigits,b.pairPositions):''}${b?`<div class="branch-sub-pair">→ ${E((b.pairDigits||[]).join(' · '))}</div><small>${b.lastOverlap}/3 · streak ${b.streak} · score ${b.score.toFixed(1)}</small>`:''}</div>`}
function mainCard(v){if(!v?.target)return '<div class="branch-empty">Нет целевого тиража.</div>';if(!v.active)return `<div class="branch-empty">${E(v.target.date)} ${E(v.target.time)} · недостаточно данных.</div>`;const fr=frozen(v.target),b=fr?.branch||snap(v.active),p=fr?.forecastDigits||v.picks.map(x=>x.digit),last=fr?.latestAtFreeze||(v.latest?{id:v.latest.id,date:v.latest.date,time:v.latest.time,digits:combo(v.latest)}:null);return `<div class="branch-current-row"><div class="branch-current-fact"><label>ТЕКУЩИЙ ФАКТ</label><b>${last?`${E(last.date)} · ${E(last.time)} · №${E(last.id)}`:'—'}</b>${last?triple(last.digits):''}</div><div class="branch-target-box"><label>ЦЕЛЕВОЙ ТИРАЖ</label><strong>${E(v.target.time)}</strong><span>${E(v.target.date)} · №${E(v.target.id)}</span><span class="branch-freeze-badge ${fr?'pending':'preview'}">${fr?'🔒 FROZEN · ОЖИДАЕТ':'ПРЕДПРОСМОТР'}</span></div></div><div class="branch-core-grid"><div class="branch-core-box"><label>ВЕТКА</label><div class="branch-ds"><b>D${b.D}</b><b>S${b.S>0?'+':''}${b.S}</b></div><span>${E(fr?.decision||v.decision)} · streak ${b.streak}</span></div><div class="branch-core-box"><label>ИСТОЧНИК</label><b>${E(b.sourceDate)} · ${E(b.sourceTime)}</b>${triple(b.sourceDigits,b.pairPositions)}<span>последний перенос ${b.lastOverlap}/3 · score ${b.score.toFixed(1)}</span></div><div class="branch-core-box branch-prediction"><label>2 ЦИФРЫ НА ЦЕЛЬ</label>${pair(p)}<span>из позиций ${(b.pairPositions||[]).map(i=>'ABC'[i]).join(' + ')}</span></div></div>${fr?`<div class="branch-freeze-line">🔒 Поставлен ${E(stamp(fr.createdAt))}. Запись не переписывается.</div>`:''}`}
function arrowView(v){if(!v?.active)return '';const b=v.active;return `<div class="branch-arrow-caption"><b>${E(b.label)}</b><span>${E(b.sourceDate)} ${E(b.sourceTime)} → ${E(v.target.date)} ${E(v.target.time)}</span></div><div class="branch-arrow-canvas" id="branchArrowCanvas"><div class="branch-arrow-source"><small>ИСТОЧНИК</small>${b.sourceDigits.map((n,i)=>`<span class="branch-arrow-node source ${b.pair?.positions?.includes(i)?'selected':''}" data-sp="${i}">${n}</span>`).join('')}</div><div class="branch-arrow-target"><small>ЦЕЛЬ</small>${v.picks.map((x,i)=>`<span class="branch-arrow-node target" data-ts="${i}">${x.digit}</span>`).join('')}</div><svg class="branch-mini-svg"></svg></div><div class="branch-arrow-note">Стрелки только показывают два выбранных переноса и не меняют расчёт.</div>`}
function drawArrows(){if(!arrows||!cur)return;const c=$('#branchArrowCanvas'),svg=c?.querySelector('svg');if(!c||!svg)return;const R=c.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 ${R.width} ${R.height}`);svg.innerHTML='<defs><marker id="ba" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#45d8ff"/></marker></defs>';cur.picks.forEach((p,i)=>{const s=c.querySelector(`[data-sp="${p.sourcePos}"]`),t=c.querySelector(`[data-ts="${i}"]`);if(!s||!t)return;const a=s.getBoundingClientRect(),b=t.getBoundingClientRect(),x1=a.left-R.left+a.width/2,y1=a.top-R.top+a.height/2,x2=b.left-R.left+b.width/2,y2=b.top-R.top+b.height/2,path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M${x1} ${y1} C${(x1+x2)/2} ${y1},${(x1+x2)/2} ${y2},${x2} ${y2}`);path.setAttribute('class','branch-mini-path');path.setAttribute('marker-end','url(#ba)');svg.appendChild(path)})}
function card(r){const matched=[...(r.matchedDigits||[])],f=(r.forecastDigits||[]).map(n=>{const i=matched.indexOf(n),ok=i>=0;if(ok)matched.splice(i,1);return digit(n,r.fact?(ok?'hit':'miss'):'forecast')}).join(''),fact=r.fact?(r.fact||[]).map(n=>digit(n,'fact')).join(''):'—',res=r.status==='pending'?'ОЖИДАЕТ':r.status==='hit'?'2/2':r.status==='part'?'1/2':'0/2';return `<article class="branch-archive-item ${r.status}"><div class="branch-archive-item-head"><div><b>${E(r.targetDate)} · ${E(r.targetTime)}${r.factDrawId?` · №${E(r.factDrawId)}`:''}</b><span>поставлен ${E(stamp(r.createdAt))}</span></div><strong>${res}</strong></div><div class="branch-archive-grid"><div><label>FROZEN</label><div class="branch-inline-digits">${f}</div></div><div><label>ФАКТ</label><div class="branch-inline-digits">${fact}</div></div><div><label>ВЕТКА</label><b>${E(r.branch?.label||'—')}</b><span>${E(r.decision||'—')} · streak ${E(r.branch?.streak??'—')}</span></div><div><label>ИСТОЧНИК</label><b>${E(r.branch?.sourceDate||'—')} · ${E(r.branch?.sourceTime||'—')}</b><span>${E((r.branch?.sourceDigits||[]).join(''))} · перенос ${r.sourceOverlap==null?'—':r.sourceOverlap+'/3'}</span></div></div><div class="branch-archive-foot">совпали: <b>${E((r.matchedDigits||[]).join(' · ')||'—')}</b>${r.manual?' · ручная':' · авто'} фиксация</div></article>`}
function renderArchive(){let a=[...rows].sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt));if(filter!=='all')a=a.filter(r=>r.status===filter);$('#branchArchive').innerHTML=a.length?a.map(card).join(''):'<div class="branch-empty">Записей пока нет.</div>';const settled=rows.filter(r=>r.status!=='pending'),h=settled.filter(r=>r.status==='hit').length,p=settled.filter(r=>r.status==='part').length,m=settled.filter(r=>r.status==='miss').length;$('#branchStats').innerHTML=[['Frozen',rows.length],['Проверено',settled.length],['2/2',h],['1/2',p],['0/2',m],['2/2 %',settled.length?(100*h/settled.length).toFixed(1)+'%':'0.0%']].map(([a,b])=>`<div class="branch-stat"><span>${a}</span><b>${b}</b></div>`).join('');$$('[data-branch-filter]').forEach(b=>b.classList.toggle('active',b.dataset.branchFilter===filter))}
function render(){if(!$('#branchForecastCard'))return;cur=analyze();settle();if(auto&&cur)freeze(cur,false,true);$('#branchForecastCard').innerHTML=mainCard(cur);const fr=cur?.target?frozen(cur.target):null,p=fr?.forecastDigits||cur?.picks?.map(x=>x.digit)||[];$('#branchCompactLine').textContent=cur?.active?`${cur.target.time} · ${cur.active.label} · ${p.join(' / ')} · ${fr?'FROZEN':'предпросмотр'}`:'нет расчёта';$('#branchWhyBody').innerHTML=cur?.active?`<div class="branch-subcards">${sub('КОНТРОЛЬ ТОГО ЖЕ D · S0',snap(cur.controlS0))}${sub('ДАЛЬНЯЯ НИТЬ D8–D14',snap(cur.extendedSignal))}</div>`:'';const btn=$('#branchFreezeBtn');if(btn){btn.disabled=!!fr||!cur?.active||late(cur?.target);btn.textContent=fr?'🔒 Уже зафиксирован':'🔒 Зафиксировать'}const st=$('#branchArrowStage');st.classList.toggle('hidden',!arrows);st.innerHTML=arrows?arrowView(cur):'';$('#branchExpanded').classList.toggle('hidden',collapsed);$('#branchCollapseArrow').textContent=collapsed?'⌄':'⌃';$('#branchArrowToggle').textContent=arrows?'↗ Скрыть стрелки':'↗ Показать стрелки';$('#branchAutoFreeze').checked=auto;renderArchive();requestAnimationFrame(drawArrows)}
function reserve(name){const title=name==='steps'?'🪜 СТУПЕНИ':'▥ ТРИ СТОЛБА',key=name==='steps'?'pozitron.labMatrix.stepsArchive.v1':'pozitron.labMatrix.threeColumnsArchive.v1';$('#labReservedPanel').innerHTML=`<div class="lab-reserved-box"><h2>${title}</h2><p>Место зарезервировано. Будущий модуль получит отдельный движок, frozen и архив и не будет смешиваться с «Веткой».</p><small>${key}</small></div>`}
function select(name){module=name;saveUi();$$('[data-lab-module]').forEach(b=>b.classList.toggle('active',b.dataset.labModule===name));const br=$('#labBranchPanel'),ar=$('.branch-archive-card'),rs=$('#labReservedPanel'),on=name==='branch';br.classList.toggle('hidden',!on);ar.classList.toggle('hidden',!on);rs.classList.toggle('hidden',on);if(on)render();else reserve(name)}
function html(){return `<div id="labBranchWorkspace" class="branch-workspace"><section class="card lab-workspace-head"><div><h2>🧪 LAB MATRIX</h2><p>лаборатория независимых прогнозных модулей · frozen и архивы не смешиваются</p></div><span class="lab-honest-badge">🔒 ЧЕСТНЫЙ FROZEN</span><div class="lab-module-tabs"><button class="lab-module-tab" data-lab-module="branch">🧬 Ветка на следующий тираж</button><button class="lab-module-tab" data-lab-module="steps">🪜 Ступени · место</button><button class="lab-module-tab" data-lab-module="columns">▥ Три столба · место</button></div></section><section id="labBranchPanel" class="card branch-lab-card"><div class="branch-lab-titlebar"><button id="branchCollapseBtn" class="branch-title-button"><span>🧬 <b>ВЕТКА НА СЛЕДУЮЩИЙ ТИРАЖ</b><small id="branchCompactLine">расчёт…</small></span><span id="branchCollapseArrow">⌃</span></button><label class="branch-auto-toggle"><span>автофиксация</span><input id="branchAutoFreeze" type="checkbox" checked><i></i></label></div><div id="branchExpanded"><div id="branchForecastCard"></div><div class="branch-actions"><button id="branchRefreshBtn" class="branch-primary-btn">↻ Пересчитать экран</button><button id="branchArrowToggle" class="branch-secondary-btn">↗ Показать стрелки</button><button id="branchFreezeBtn" class="branch-secondary-btn">🔒 Зафиксировать</button></div><div id="branchArrowStage" class="branch-arrow-stage hidden"></div><details class="branch-why"><summary>Контроль S0 · дальняя нить</summary><div id="branchWhyBody"></div></details></div></section><section id="labReservedPanel" class="card lab-reserved hidden"></section><section class="card branch-archive-card"><div class="branch-archive-head"><div><h2>АРХИВ ВЕТКИ</h2><p>постановка → цель → frozen → факт → проверка двух цифр</p></div><button id="branchCheckFactsBtn" class="branch-secondary-btn">↻ Проверить факты</button></div><div id="branchStats" class="branch-stats"></div><div class="branch-archive-filters"><button data-branch-filter="all">ВСЕ</button><button data-branch-filter="hit">2/2</button><button data-branch-filter="part">1/2</button><button data-branch-filter="miss">0/2</button><button data-branch-filter="pending">ОЖИДАЮТ</button></div><div id="branchArchive"></div></section></div>`}
function inject(){const lab=$('#labView');if(!lab||$('#labBranchWorkspace'))return;[...lab.children].forEach(x=>x.classList.add('branch-legacy-hidden'));lab.insertAdjacentHTML('afterbegin',html())}
function bind(){if(bound)return;bound=true;$('#branchCollapseBtn').onclick=()=>{collapsed=!collapsed;saveUi();render()};$('#branchArrowToggle').onclick=()=>{arrows=!arrows;saveUi();render()};$('#branchAutoFreeze').onchange=e=>{auto=!!e.target.checked;saveUi();render()};$('#branchFreezeBtn').onclick=()=>{freeze(cur,true,false);render()};$('#branchRefreshBtn').onclick=async()=>{await refreshData();render();toast('Данные обновлены. Старый frozen не изменён.')};$('#branchCheckFactsBtn').onclick=async()=>{await refreshData();settle(true);render()};document.querySelector('.branch-archive-filters').onclick=e=>{const b=e.target.closest('[data-branch-filter]');if(b){filter=b.dataset.branchFilter;saveUi();renderArchive()}};$$('[data-lab-module]').forEach(b=>b.onclick=()=>select(b.dataset.labModule));window.addEventListener('resize',()=>requestAnimationFrame(drawArrows),{passive:true})}
function chrome(){const v=document.querySelector('.version');if(v)v.textContent='отдельное приложение · v1.7.0 · FULL 48 GRID · LAB BRANCH';const sync=()=>document.body.classList.toggle('branch-lab-active',$('#labView')?.classList.contains('active'));sync();document.addEventListener('click',e=>{if(e.target.closest('[data-tab]'))setTimeout(sync,0)})}
async function init(){loadUi();inject();bind();await refreshData();settle();select(module);chrome()}
function boot(){init().catch(e=>console.error('LAB BRANCH init',e))}if(document.readyState==='complete')boot();else window.addEventListener('load',boot,{once:true});
window.TOP3BranchLab={render,analyze,freeze:()=>freeze(cur,true,false),settle,readArchive:()=>JSON.parse(JSON.stringify(rows)),refresh:async()=>{await refreshData();render()}};
})();
